bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set -g mouse on
set -g mode-keys vi
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',*:RGB'
